token_exprs = [#regex for matching the characters to lexemes
        (r';', 'TK_SEM'),
        (r'[ \t]+', 'SKIP'), #matching whitespace
        (r'[\n]', 'NEWLINE'),
        (r'#[^\n]*', 'COMMENT'), #matching comments
        (r':', 'TK_ASSIGNOP'),
        (r'map_insert', 'TK_MAPINSERT'),
        (r'map_remove', 'TK_MAPREMOVE'),
        (r'assign', 'TK_ASSIGN'),
        (r'var', 'TK_VAR'),
        (r'main', 'TK_MAIN'),
        (r'end_main', 'TK_ENDMAIN'),
        (r'int', 'TK_INT'),
        (r'real', 'TK_REAL'),
        (r'if', 'TK_IF'),
        (r'end_if', 'TK_ENDIF'),
        (r'global', 'TK_GLOBAL'),
        (r'input', 'TK_INPUT'),
        (r'output', 'TK_OUTPUT'),
        (r'while', 'TK_WHILE'),
        (r'end_while', 'TK_ENDWHILE'),
        (r'char', 'TK_CHAR'),
        (r'function', 'TK_FUNCTION'),
        (r'end_function', 'TK_ENDFUNCTION'),
        (r'elseif', 'TK_ELSEIF'),
        (r'else', 'TK_ELSE'),
        (r'record', 'TK_RECORD'),
        (r'end_record', 'TK_ENDRECORD'),
        (r'array', 'TK_ARRAY'),
        (r'map', 'TK_MAP'),
        (r'get', 'TK_GET'),
        (r'puts', 'TK_PUTS'),
        (r'put', 'TK_PUT'),
        (r'return', 'TK_RETURN'),
        (r'break', 'TK_BREAK'),
        (r'call', 'TK_CALL'),
        (r'\[', 'TK_SQL'),
        (r'\]', 'TK_SQR'),
        (r'\,', 'TK_COMMA'),
        (r'\.', 'TK_DOT'),
        (r'\(', 'TK_OP'),
        (r'\)', 'TK_CL'),
        (r'\+', 'TK_PLUS'),
        (r'\-', 'TK_MINUS'),
        (r'\*', 'TK_MUL'),
        (r'\/', 'TK_DIV'),
        (r'\%', 'TK_MOD'),
        (r'\&', 'TK_AND'),
        (r'\|', 'TK_OR'),
        (r'!=', 'TK_NE'),
        (r'\!', 'TK_NOT'),
        (r'<=', 'TK_LE'),
        (r'<', 'TK_LT'),
        (r'==', 'TK_EQ'),
        (r'>=', 'TK_GE'),
        (r'>', 'TK_GT'),
        (r'\"[A-Za-z0-9_.,:? ]*"', 'TK_STRING'),
        (r'V_[A-Za-z_][A-Za-z0-9_]*', 'TK_ID'),
        (r'F_[A-Za-z_][A-Za-z0-9_]*', 'TK_FUNID'),
        (r'R_[A-Za-z_][A-Za-z0-9_]*', 'TK_RECORDID'),
        (r'M_[A-Za-z_][A-Za-z0-9_]*', 'TK_MAPID'),
        (r'A_[A-Za-z_][A-Za-z0-9_]*', 'TK_ARRAYID'),
        (r'\'\'\'[A-Za-z_][A-Za-z0-9_]*\'\'\'', 'TK_MAPFIELD'),
        (r'\'[A-Za-z0-9_.,:? ]\'', 'TK_CHR'),
        (r'[0-9]+.[0-9]+', 'TK_RNUM'),
        (r'[0-9]+', 'TK_NUM'), #Integer literals 
        (r'[A-Za-z0-9_,.|:?]', 'TK_CHR'),
]